import { randomBytes } from "crypto";
import type { OrderPreview } from "./types";

// ─── Preview Store ──────────────────────────────────────────────
// Order previews are ephemeral: generated by the AI, confirmed by the user,
// then executed. They expire after 5 minutes and are single-use.
//
// Production: Upstash Redis — atomic GETDEL prevents double-execution
//             across serverless instances.
// Development: In-memory Map fallback.

const PREVIEW_TTL_S = 300; // 5 minutes — user may need time to review
const REDIS_PREFIX = "preview:";

// ── Redis client (reuse from ratelimit config) ──

let redis: import("@upstash/redis").Redis | null = null;

async function getRedis() {
  if (redis) return redis;
  const url = process.env.UPSTASH_REDIS_REST_URL;
  const token = process.env.UPSTASH_REDIS_REST_TOKEN;
  if (url && token) {
    const { Redis } = await import("@upstash/redis");
    redis = new Redis({ url, token });
    return redis;
  }
  return null;
}

// ── In-memory fallback (development only) ──

interface StoredPreview {
  preview: OrderPreview;
  userId: string;
  createdAt: number;
}

const memStore = new Map<string, StoredPreview>();
const MAX_MEM_PREVIEWS = 200;

function memCleanup() {
  const now = Date.now();
  for (const [id, entry] of memStore) {
    if (now - entry.createdAt > PREVIEW_TTL_S * 1000) {
      memStore.delete(id);
    }
  }
}

// ── Public API ──

/** Generate a cryptographically random preview ID */
function generatePreviewId(): string {
  return `prev_${randomBytes(16).toString("hex")}`;
}

/**
 * Store a preview and return its ID.
 * TTL: 5 minutes. Single-use.
 */
export async function storePreview(
  preview: Omit<OrderPreview, "previewId">,
  userId: string
): Promise<string> {
  const previewId = generatePreviewId();
  const fullPreview: OrderPreview = { ...preview, previewId };
  const payload = JSON.stringify({ preview: fullPreview, userId });

  const r = await getRedis();
  if (r) {
    // Redis: SET with TTL — auto-expires
    await r.set(`${REDIS_PREFIX}${previewId}`, payload, { ex: PREVIEW_TTL_S });
  } else {
    // In-memory fallback
    memCleanup();
    if (memStore.size >= MAX_MEM_PREVIEWS) {
      // Find truly oldest by createdAt timestamp
      let oldestId: string | null = null;
      let oldestTime = Infinity;
      for (const [id, entry] of memStore) {
        if (entry.createdAt < oldestTime) {
          oldestTime = entry.createdAt;
          oldestId = id;
        }
      }
      if (oldestId) memStore.delete(oldestId);
    }
    memStore.set(previewId, { preview: fullPreview, userId, createdAt: Date.now() });
  }

  return previewId;
}

/**
 * Atomically retrieve and consume a preview.
 * Returns null if expired, already consumed, or belongs to a different user.
 *
 * Redis: uses GETDEL for true atomic single-use across all instances.
 * Memory: synchronous delete (safe in single-threaded Node.js).
 */
export async function consumePreview(
  previewId: string,
  userId: string
): Promise<OrderPreview | null> {
  const r = await getRedis();

  if (r) {
    // Atomic check-and-delete via Lua script — ownership verified BEFORE deletion.
    // Prevents DOS where attacker consumes another user's preview via GETDEL.
    const key = `${REDIS_PREFIX}${previewId}`;
    const luaScript = `
      local val = redis.call('GET', KEYS[1])
      if not val then return nil end
      local data = cjson.decode(val)
      if data.userId ~= ARGV[1] then return nil end
      redis.call('DEL', KEYS[1])
      return val
    `;
    try {
      const raw = await r.eval(luaScript, [key], [userId]) as string | null;
      if (!raw) return null;
      const data = typeof raw === "string" ? JSON.parse(raw) : raw;
      return data.preview as OrderPreview;
    } catch {
      // Fallback if Lua not supported — use SETNX lock to prevent TOCTOU race
      const lockKey = `${REDIS_PREFIX}lock:${previewId}`;
      const locked = await r.set(lockKey, "1", { ex: 10, nx: true });
      if (!locked) return null; // Another request is consuming this preview
      try {
        const raw = await r.get(key);
        if (!raw) return null;
        const data = typeof raw === "string" ? JSON.parse(raw) : raw;
        if (data.userId !== userId) return null;
        await r.del(key);
        return data.preview as OrderPreview;
      } finally {
        await r.del(lockKey).catch(() => {}); // Cleanup lock
      }
    }
  }

  // In-memory fallback
  const entry = memStore.get(previewId);
  if (!entry) return null;
  if (entry.userId !== userId) return null;
  if (Date.now() - entry.createdAt > PREVIEW_TTL_S * 1000) {
    memStore.delete(previewId);
    return null;
  }

  // Delete before returning — atomic in single-threaded JS
  memStore.delete(previewId);
  return entry.preview;
}

/**
 * Get a preview without consuming it (for display/verification).
 */
export async function getPreview(
  previewId: string,
  userId: string
): Promise<OrderPreview | null> {
  const r = await getRedis();

  if (r) {
    const raw = await r.get(`${REDIS_PREFIX}${previewId}`);
    if (!raw) return null;
    const data = typeof raw === "string" ? JSON.parse(raw) : raw;
    if (data.userId !== userId) return null;
    return data.preview as OrderPreview;
  }

  // In-memory fallback
  const entry = memStore.get(previewId);
  if (!entry) return null;
  if (entry.userId !== userId) return null;
  if (Date.now() - entry.createdAt > PREVIEW_TTL_S * 1000) {
    memStore.delete(previewId);
    return null;
  }
  return entry.preview;
}
