import { randomBytes } from "crypto";
import type { OrderPreview } from "./types";
import { prisma } from "../db";

/* ------------------------------------------------------------------ */
/*  Order preview store — Postgres primary, in-memory last-resort.     */
/* ------------------------------------------------------------------ */
//
// Order previews are ephemeral: generated by the AI, confirmed by the
// user, then executed. Each preview is single-use, scoped to its
// owning userId, and expires after 5 minutes.
//
// History:
//   v1: Upstash Redis primary (atomic GETDEL + Lua-script ownership
//       check), in-memory fallback. Removed in Phase 8a.
//   v2 (this file): Postgres primary. Atomic single-use guarantee via
//       `DELETE ... WHERE id = ? AND user_id = ? AND expires_at > NOW()
//       RETURNING payload` — ownership, TTL, and consume happen inside
//       one statement so a different user can't burn someone else's
//       preview, and a single retry can't double-execute.

const PREVIEW_TTL_S = 300; // 5 minutes

/* ─── In-memory fallback (used only on Postgres outage) ─── */

interface MemEntry {
  preview: OrderPreview;
  userId: string;
  createdAt: number;
}

const memStore = new Map<string, MemEntry>();
const MAX_MEM_PREVIEWS = 200;

function memCleanup(): void {
  const now = Date.now();
  for (const [id, entry] of memStore) {
    if (now - entry.createdAt > PREVIEW_TTL_S * 1000) memStore.delete(id);
  }
}

function memEvictOldest(): void {
  if (memStore.size < MAX_MEM_PREVIEWS) return;
  let oldestId: string | null = null;
  let oldestTime = Infinity;
  for (const [id, entry] of memStore) {
    if (entry.createdAt < oldestTime) {
      oldestTime = entry.createdAt;
      oldestId = id;
    }
  }
  if (oldestId) memStore.delete(oldestId);
}

/* ─── Logging throttle for PG outage warnings ─── */

let lastPgWarnAt = 0;
const PG_WARN_INTERVAL_MS = 60_000;

function warn(label: string, err: unknown): void {
  const now = Date.now();
  if (now - lastPgWarnAt > PG_WARN_INTERVAL_MS) {
    lastPgWarnAt = now;
    console.warn(
      `[preview-store] ${label} failed:`,
      err instanceof Error ? err.message : err,
    );
  }
}

/* ─── Background cleanup of expired Postgres rows ─── */

const CLEANUP_INTERVAL_MS = 5 * 60_000;
let cleanupTimer: ReturnType<typeof setInterval> | null = null;

function ensureCleanupTimer(): void {
  if (cleanupTimer || typeof setInterval === "undefined") return;
  cleanupTimer = setInterval(() => {
    void prisma
      .$executeRaw`DELETE FROM order_previews WHERE expires_at < NOW();`
      .catch((err: unknown) => warn("periodic cleanup", err));
  }, CLEANUP_INTERVAL_MS);
  if (typeof cleanupTimer === "object" && cleanupTimer && "unref" in cleanupTimer) {
    (cleanupTimer as unknown as { unref: () => void }).unref();
  }
}

/* ─── Public API ─── */

/** Generate a cryptographically random preview ID. */
function generatePreviewId(): string {
  return `prev_${randomBytes(16).toString("hex")}`;
}

/**
 * Persist a preview and return its ID. The preview is owner-scoped to
 * `userId`; only that same user can later consume it. TTL is 5 minutes.
 */
export async function storePreview(
  preview: Omit<OrderPreview, "previewId">,
  userId: string,
): Promise<string> {
  ensureCleanupTimer();
  const previewId = generatePreviewId();
  const fullPreview: OrderPreview = { ...preview, previewId };

  try {
    await prisma.$executeRaw`
      INSERT INTO order_previews (id, user_id, payload, expires_at)
      VALUES (
        ${previewId},
        ${userId},
        ${fullPreview as object}::jsonb,
        NOW() + (${PREVIEW_TTL_S}::int * INTERVAL '1 second')
      )
      ON CONFLICT (id) DO NOTHING;
    `;
    return previewId;
  } catch (err) {
    warn("storePreview", err);
    // Fall back to in-memory so order flow keeps working under PG outage.
    memCleanup();
    memEvictOldest();
    memStore.set(previewId, { preview: fullPreview, userId, createdAt: Date.now() });
    return previewId;
  }
}

/**
 * Atomically retrieve and consume a preview. Returns null if the
 * preview doesn't exist, has expired, has already been consumed, or
 * belongs to a different user.
 *
 * Atomicity: the DELETE...RETURNING acquires a row-level lock and
 * applies the userId + expires_at predicates inside the same
 * statement. Two concurrent confirms for the same previewId serialise
 * on the lock and only one returns a row.
 */
export async function consumePreview(
  previewId: string,
  userId: string,
): Promise<OrderPreview | null> {
  ensureCleanupTimer();
  try {
    const rows = await prisma.$queryRaw<{ payload: OrderPreview }[]>`
      DELETE FROM order_previews
      WHERE id = ${previewId}
        AND user_id = ${userId}
        AND expires_at > NOW()
      RETURNING payload;
    `;
    if (rows.length > 0) return rows[0].payload;
    // Not in PG (or wrong user / expired) — try memory fallback in case
    // the preview was stored under PG outage.
  } catch (err) {
    warn("consumePreview", err);
  }

  const entry = memStore.get(previewId);
  if (!entry) return null;
  if (entry.userId !== userId) return null;
  if (Date.now() - entry.createdAt > PREVIEW_TTL_S * 1000) {
    memStore.delete(previewId);
    return null;
  }
  memStore.delete(previewId);
  return entry.preview;
}

/**
 * Read a preview without consuming it (for display / verification).
 * Returns null if missing, expired, or owned by another user.
 */
export async function getPreview(
  previewId: string,
  userId: string,
): Promise<OrderPreview | null> {
  ensureCleanupTimer();
  try {
    const rows = await prisma.$queryRaw<{ payload: OrderPreview }[]>`
      SELECT payload
      FROM order_previews
      WHERE id = ${previewId}
        AND user_id = ${userId}
        AND expires_at > NOW()
      LIMIT 1;
    `;
    if (rows.length > 0) return rows[0].payload;
  } catch (err) {
    warn("getPreview", err);
  }

  const entry = memStore.get(previewId);
  if (!entry) return null;
  if (entry.userId !== userId) return null;
  if (Date.now() - entry.createdAt > PREVIEW_TTL_S * 1000) {
    memStore.delete(previewId);
    return null;
  }
  return entry.preview;
}
