import { randomBytes } from "crypto";
import type { OrderPreview } from "./types";

// ─── In-Memory Preview Store ─────────────────────────────────────
// Order previews are ephemeral: generated by the AI, confirmed by the user,
// then executed. They expire after 60 seconds and are single-use.

interface StoredPreview {
  preview: OrderPreview;
  userId: string;     // Solana address of the user who requested it
  createdAt: number;
  used: boolean;
}

const PREVIEW_TTL_MS = 60_000; // 60 seconds
const MAX_PREVIEWS = 1000;     // prevent memory leak
const store = new Map<string, StoredPreview>();

/** Generate a unique preview ID */
function generatePreviewId(): string {
  return `prev_${randomBytes(16).toString("hex")}`;
}

/** Periodically clean up expired previews */
function cleanup() {
  const now = Date.now();
  for (const [id, entry] of store) {
    if (now - entry.createdAt > PREVIEW_TTL_MS || entry.used) {
      store.delete(id);
    }
  }
}

// Run cleanup every 30 seconds
let cleanupInterval: ReturnType<typeof setInterval> | null = null;
function ensureCleanup() {
  if (!cleanupInterval) {
    cleanupInterval = setInterval(cleanup, 30_000);
    // Don't block process exit
    if (typeof cleanupInterval === "object" && "unref" in cleanupInterval) {
      cleanupInterval.unref();
    }
  }
}

/**
 * Store a preview and return its ID.
 * The preview expires after 60 seconds.
 */
export function storePreview(preview: Omit<OrderPreview, "previewId">, userId: string): string {
  ensureCleanup();

  // Evict oldest if at capacity
  if (store.size >= MAX_PREVIEWS) {
    const oldest = store.keys().next().value;
    if (oldest) store.delete(oldest);
  }

  const previewId = generatePreviewId();
  const fullPreview: OrderPreview = { ...preview, previewId };

  store.set(previewId, {
    preview: fullPreview,
    userId,
    createdAt: Date.now(),
    used: false,
  });

  return previewId;
}

/**
 * Retrieve and consume a preview.
 * Returns null if expired, already used, or belongs to a different user.
 * This is single-use: the preview is atomically deleted from the store on consumption
 * to prevent race conditions where concurrent requests could both consume the same preview.
 */
export function consumePreview(previewId: string, userId: string): OrderPreview | null {
  const entry = store.get(previewId);
  if (!entry) return null;

  // Security checks
  if (entry.used) return null;
  if (entry.userId !== userId) return null;
  if (Date.now() - entry.createdAt > PREVIEW_TTL_MS) {
    store.delete(previewId);
    return null;
  }

  // Atomically delete from store to prevent double-consumption.
  // Map.delete + mark used ensures even if two calls race past the
  // `store.get` check, only the first one gets the preview.
  store.delete(previewId);
  entry.used = true;
  return entry.preview;
}

/**
 * Get a preview without consuming it (for display purposes).
 * Does NOT mark as used.
 */
export function getPreview(previewId: string, userId: string): OrderPreview | null {
  const entry = store.get(previewId);
  if (!entry) return null;
  if (entry.userId !== userId) return null;
  if (entry.used) return null;
  if (Date.now() - entry.createdAt > PREVIEW_TTL_MS) {
    store.delete(previewId);
    return null;
  }
  return entry.preview;
}
